version: '3.3'
services:
  # 自定义的服务名
  database:
    # 镜像
    image: mongo:latest
    restart: always
    # 卷
    #volumes:
    #  - /data/db:/data/db
    networks:
      - webapp-network
  web:
    # 构建目录
    build: ./
    image: snake-api-mini
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - 3004:3004
    networks:
      - webapp-network
    command: ["bash", "-c", "sed -i 's/\r//g' ./wait-for-it.sh && bash ./wait-for-it.sh database:27017 --strict -- npm run start"]
networks:
  webapp-network:
    driver: bridge
